### ISSUE TITLE
Notification script support for Grafana v6.x

### ISSUE THREAD

**Issue by PinkFrog** [mmarodin/icinga2-plugins#9]
Hi, 
is there a support for Grafana v6 planned? 
Great work with the HTML e-Mails, thanks for that! 

Best regards Alicia

**Comment by 42bios** [comment]
* > Grafana v7

**Comment by 42bios** [comment]
> Hi,
> is there a support for **Grafana v7** planned?
> Great work with the HTML e-Mails, thanks for that!
> 
> Best regards Alicia

**Comment by mmarodin** [comment]
@PinkFrog sorry for the delay, I've just tried to update my Grafana from v5.4.2 to v6.7.4, and my notification scripts are working perfectly.
You have to use all variables, like panelid or similar.
You should look at _/var/log/icinga2/icinga2.log_ file and check if there are some errors like this:
### mail-service-perfdata-notification.py: error: argument --panelid/-a: expected one argument
If so some variable of the service is missing.

Now I will try with the v7.x release ...

**Comment by mmarodin** [comment]
Hi @42bios , I've just tried to update my environment to Grafana v7.1.5.
My notification scripts are working also with this release, but you have to install the grafana image render plugin, because [PhantomJS support has been removed](https://grafana.com/docs/grafana/latest/installation/upgrading/#phantomjs-removed).

_# grafana-cli plugins install grafana-image-renderer
installing grafana-image-renderer @ 2.0.0
from: https://grafana.com/api/plugins/grafana-image-renderer/versions/2.0.0/download
into: /var/lib/grafana/plugins
✔ Installed grafana-image-renderer successfully
Restart grafana after installing plugins . <service grafana-server restart>_
